name: AISOC Project Submission
description: "Submit your project to get a progress report!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project Name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your project. What is it about? What type of app have you built? What is it doing? What problem is it solving?
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Project Repository URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: textarea
    id: logfile
    attributes:
      label: Evals Log File
      description: Drag and drop your evals log file below or use the clip icon to upload the file from your computer.
    validations:
      required: true
  - type: input
    id: app
    attributes:
      label: Streamlit App URL
      description: URL to the application deployed on Streamlit.
    validations:
      required: true
  - type: input
    id: video
    attributes:
      label: Project Video (optional)
      description: Provide a short demo video of your project. Video should be 5-6mins at most.
    validations:
      required: false